### ISSUE TITLE
gem install still gets 2.0.5

### ISSUE THREAD

**Issue by plynchnlm** [Compass/compass-rails#255] opened 2015-12-22 20:05 UTC
I see 3.0.0 of compass-rails is in the master branch, but "gem install compass-rails" installs version 2.0.5.

**Comment by mvastola** [comment] 2015-12-27 19:08
This is related to #254. 3.0.0 has not yet been released, apparently. 

Information as to what features are incomplete/lack sufficient testing would be appreciated from the devs as I'd be interested in assisting to get it pushed out.

**Comment by mvastola** [comment] 2016-01-23 18:50
@plynchnlm compass-rails 3.0.0 was just released last night. Try now and close this issue if everything works.

**Comment by craigmcnamara** [comment] 2016-01-23 23:11
This is not a bug, the release was never made. Master versions numbers are the releases to come.

**Closed by craigmcnamara** 2016-01-23 23:11 UTC
